# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
 languageCode: ko
 contentDir: content/ko
 weight: 1
 title: 김예은의 포트폴리오
 params:
   description: 김예은의 포트폴리오 웹 사이트...

en:
 languageCode: en
 contentDir: content/en
 weight: 2
 title: Yeeun-Kim's Portfolio
 params:
   description: Portfolio website of Yeeun Kim...
