# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /#bio
    weight: 10

  - name: Resumé
    url: experience/
    weight: 20

  - name: Projects
    url: projects/
    weight: 30

  - name: Research
    identifier: Research
    url: /#research
    weight: 40
    hasChildren: true
  - name: Tech
    parent: Research
    url: /#tech
    weight: 41
  - name: Related Courses
    parent: Research
    url: /#related-courses
    weight: 42

  - name: Courses
    identifier: Courses
    url: courses/
    weight: 50
    hasChildren: true
  - name: All Courses
    parent: Courses
    url: /courses/
    weight: 51
  - name: Current Courses
    parent: Courses
    url: /courses/current/
    weight: 52
  - name: Completed Courses
    parent: Courses
    url: /courses/completed/
    weight: 52


  - name: Contact
    url: contact/
    weight: 60