# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: teal

favicon: "/media/icon.png"

# SEO
marketing:
  seo:
    site_type: Person
    org_name: '전북대 컴퓨터인공지능학부'
    description: '전북대학교 컴퓨터인공지능학부 김예은의 포트폴리오입니다.'
    keywords: ['김예은', '전북대학교', '전북대', '컴퓨터인공지능학부']
    image: 'media/sharing.jpg'
  verification:
    google: '' # static 폴더에 HTML 파일 인증 방식 추가함.

# Site header 
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    show_logo: ture
    logo:
      filename: 'logo.png'
      height: 100

# Site footer
footer:
  copyright:
    notice: '© {2025} 김예은(Yeeun-Kim). This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  search:
    provider: pagefind
    enable: true

custom_css:
  - "css/custom.css"